export const allMatchCardData = [
  {
    text: "Total Matches",
    subtext: "5,423",
    thisMonthdata: {
      value: "16%",
      timePeriod: "this month",
      icon: {
        src: "/assets/icons/arrow-green.svg",
        alt: "green arrow",
      },
    },
    image: {
      src: "/assets/icons/total-matches-icon.svg",
      alt: "total matches",
    },
  },
  {
    text: "Verified Matches",
    subtext: "4,230",
    thisMonthdata: {
      value: "16%",
      timePeriod: "this month",
      icon: {
        src: "/assets/icons/arrow-red.svg",
        alt: "red arrow",
      },
    },
    image: {
      src: "/assets/icons/verified-icon.svg",
      alt: "verified matches",
    },
  },
  {
    text: "Active Matches",
    subtext: "230",
    image: {
      src: "/assets/icons/active-user-icon.svg",
      alt: "active user",
    },
  },
];

export const tableDataForAllMatches = [
  {
    id: "#CMP801",
    name: "Natali Craig",
    companyName: "Landing Page",
    address: "Meadow Lane Oakland",
    userType: "Invester",
  },
  {
    id: "#CMP802",
    name: "Kate Morrison",
    companyName: "CRM Admin pages",
    address: "Larry San Francisco",
    userType: "Individual Invester",
  },
  {
    id: "#CMP803",
    name: "Drew Cano",
    companyName: "Client Project",
    address: "Bagwell Avenue Ocala",
    userType: "Broker",
  },
  {
    id: "#CMP804",
    name: "Orlando Diggs",
    companyName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    userType: "Individual",
  },
  {
    id: "#CMP805",
    name: "Andi Lane",
    companyName: "App Landing Page",
    address: "Nest Lane Olivette",
    userType: "Company",
  },
  {
    id: "#CMP801",
    name: "Natali Craig",
    companyName: "Landing Page",
    address: "Meadow Lane Oakland",
    userType: "Broker",
  },
  {
    id: "#CMP802",
    name: "Kate Morrison",
    companyName: "CRM Admin pages",
    address: "Larry San Francisco",
    userType: "Individual Invester",
  },
  {
    id: "#CMP803",
    name: "Drew Cano",
    companyName: "Client Project",
    address: "Bagwell Avenue Ocala",
    userType: "Individual",
  },
  {
    id: "#CMP805",
    name: "Andi Lane",
    companyName: "App Landing Page",
    address: "Nest Lane Olivette",
    userType: "Company",
  },
  {
    id: "#CMP803",
    name: "Drew Cano",
    companyName: "Client Project",
    address: "Bagwell Avenue Ocala",
    userType: "Company",
  },
];

export const notificationTimelineData = [
  {
    notificationText: "You have a bug that needs to be fixed.",
    time: "Just now",
    image: "/assets/icons/BugBeetle.svg",
  },
  {
    notificationText: "New user registered",
    time: "59 minutes ago",
    image: "/assets/icons/User-icon.svg",
  },
  {
    notificationText: "You have a bug that needs to be fixed.",
    time: "12 hours ago",
    image: "/assets/icons/BugBeetle.svg",
  },
  {
    notificationText: "Andi Lane subscribed to you",
    time: "Today, 11:59 AM",
    image: "/assets/icons/Broadcast-icon.svg",
  },
];

export const chatData = [
  {
    id: 1,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "online",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
          "/assets/icons/chat-image2.svg",
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 2,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "offline",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const
      },
      // {
      //   id: 2,
      //   text: "Hello! Finally found the time to write to you.",
      //   time: "Now",
      //   isOwn: true,
      //   type: "text" as const,
      // },
      // {
      //   id: 3,
      //   text: "550 Fill × 294 Hug",
      //   time: "3 days ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 4,
      //   text: "OK, I NEED YOUR HELP IN DECOR",
      //   time: "2 days ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 5,
      //   text: "",
      //   time: "2 days ago",
      //   isOwn: true,
      //   type: "image" as const,
      //   images: [
      //     "/assets/icons/home-Image.svg",
      //     "/assets/icons/home-Image.svg",
      //   ],
      // },
      // {
      //   id: 6,
      //   text: "",
      //   time: "2 hours ago",
      //   isOwn: false,
      //   type: "image" as const,
      //   images: [
      //     "/assets/icons/chat-image1.svg",
      //     "/assets/icons/chat-image2.svg",
      //   ],
      // },
      // {
      //   id: 7,
      //   text: "Good question. How about just discussing it?",
      //   time: "2 hours ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 8,
      //   text: "Style.zip",
      //   time: "1 hour ago",
      //   isOwn: false,
      //   type: "file" as const,
      // },
      // {
      //   id: 9,
      //   text: "Hello! Finally found the time to write to you.",
      //   time: "Now",
      //   isOwn: true,
      //   type: "text" as const,
      // },
    ],
  },
  {
    id: 3,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 2 hours ago ",
    messages: [
      // {
      //   id: 1,
      //   text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
      //   time: "4 days ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 2,
      //   text: "Hello! Finally found the time to write to you.",
      //   time: "Now",
      //   isOwn: true,
      //   type: "text" as const,
      // },
      // {
      //   id: 3,
      //   text: "550 Fill × 294 Hug",
      //   time: "3 days ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 4,
      //   text: "OK, I NEED YOUR HELP IN DECOR",
      //   time: "2 days ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 5,
      //   text: "",
      //   time: "2 days ago",
      //   isOwn: true,
      //   type: "image" as const,
      //   images: [
      //     "/assets/icons/home-Image.svg",
      //     "/assets/icons/home-Image.svg",
      //   ],
      // },
      // {
      //   id: 6,
      //   text: "",
      //   time: "2 hours ago",
      //   isOwn: false,
      //   type: "image" as const,
      //   images: [
      //     "/assets/icons/chat-image1.svg",
      //     "/assets/icons/chat-image2.svg",
      //   ],
      // },
      // {
      //   id: 7,
      //   text: "Good question. How about just discussing it?",
      //   time: "2 hours ago",
      //   isOwn: false,
      //   type: "text" as const,
      // },
      // {
      //   id: 8,
      //   text: "Style.zip",
      //   time: "1 hour ago",
      //   isOwn: false,
      //   type: "file" as const,
      // },
      // {
      //   id: 9,
      //   text: "Hello! Finally found the time to write to you.",
      //   time: "Now",
      //   isOwn: true,
      //   type: "text" as const,
      // },
    ],
  },
  {
    id: 4,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 5 hours ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text"as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 5,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "last online 2 days ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 6,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "online",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 7,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "offline",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 8,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 2 hours ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 9,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 5 hours ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 10,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "last online 2 days ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 11,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "online",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 12,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar1.svg",
    status: "offline",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 13,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 2 hours ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
  {
    id: 14,
    name: "Eten Hunt",
    role: "Agent",
    avatar: "/assets/icons/chat-avatar-left.svg",
    status: "last online 5 hours ago ",
    messages: [
      {
        id: 1,
        text: "Hello! Finally found the time to write to you. I hope you're well and I wanted to catch up about creating interactive animations for our mobile application.",
        time: "4 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 2,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
      {
        id: 3,
        text: "550 Fill × 294 Hug",
        time: "3 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 4,
        text: "OK, I NEED YOUR HELP IN DECOR",
        time: "2 days ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 5,
        text: "",
        time: "2 days ago",
        isOwn: true,
        type: "image" as const,
        images: [
          "/assets/icons/home-Image.svg",
          "/assets/icons/home-Image.svg",
        ],
      },
      {
        id: 6,
        text: "",
        time: "2 hours ago",
        isOwn: false,
        type: "image" as const,
        images: [
          "/assets/icons/chat-image1.svg",
          "/assets/icons/chat-image2.svg",
        ],
      },
      {
        id: 7,
        text: "Good question. How about just discussing it?",
        time: "2 hours ago",
        isOwn: false,
        type: "text" as const,
      },
      {
        id: 8,
        text: "Style.zip",
        time: "1 hour ago",
        isOwn: false,
        type: "file" as const,
      },
      {
        id: 9,
        text: "Hello! Finally found the time to write to you.",
        time: "Now",
        isOwn: true,
        type: "text" as const,
      },
    ],
  },
];
